# Generated by Django 5.2 on 2026-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_role_employeeprofile_and_more'),
        ('jobapp', '0009_remove_job_skills_job_skills'),
    ]

    operations = [
        # Remove the old taggit field
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        # Add the new M2M field
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employee_profiles', to='jobapp.skill'),
        ),
    ]
